### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by mila212** [lorenzofox3/stStickyHeader#1]
Hi Lorenzo, 
Thank you for sharing this feature.
Could you please provide an example of how to use it?
I've tried to use it as an attribute in st-table directive but it didn't work.
I've also tried what you suggested in issue#3 in lrStickyHeader, but it didn't work as well.

Thank you for your help.

**Comment by zlincoln** [comment]
+1 please

**Comment by brunnurs** [comment]
+1

**Comment by lorenzofox3** [comment]
see readme
