### ISSUE TITLE
How is stStickyHeader licensed?

### ISSUE THREAD

**Issue by chrisuehlinger** [lorenzofox3/stStickyHeader#5]
Hey Lorenzo!

Can you put a LICENSE on this repository? I know lrStickyHeader and angular-smart-table are MIT Licensed. I would love to use this at my job as well, but I can't unless it has a similarly permissive license.

Thanks for all the hard work you've put into these projects!

**Comment by lorenzofox3** [comment]
Note, you can usually find the licence in the package.json
