### ISSUE TITLE
Table head and body overlap

### ISSUE THREAD

**Issue by phil-cap** [lorenzofox3/stStickyHeader#8]
@lorenzofox3 i have a bug concerning thead and tbody. There is an overlap and any manual attempts through padding and margin do not work. I have no special CSS specified otherwise.
Please see the before and after screenshots. Thank you in advance.

**Before**:

![smart-table-bug-before](https://cloud.githubusercontent.com/assets/23074664/19962239/1082419a-a1b7-11e6-9cf6-2ca5a9825c8b.PNG)

____

**After:**

![smart-table-bug-after](https://cloud.githubusercontent.com/assets/23074664/19962238/107cbe1e-a1b7-11e6-8f0f-c011f3dfe1b7.PNG)

**Comment by lorenzofox3** [comment]
I believe it is the expected result no: the head should stick, no (in your case the background of the header may be transparent, what if you put it in another color ) ? please provide plunkr otherwise

**Comment by phil-cap** [comment]
@lorenzofox3 you are right...that is the expected result. It was the background. I oversaw the fact that it is natural for the first row to be hidden once the table _switches_ to fixed mode. Thanks for the quick response.
